[package]
name = "jukeboxdesktop"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
eframe = "0.29.1"
env_logger = "0.11.5"
log = "0.4.22"
rand = "0.8.5"
serialport = "4.6.0"

[build-dependencies]
winres = "0.1.12"
