#pragma once

// LUFA config
#define USE_FLASH_DESCRIPTORS
#define USB_DEVICE_ONLY

#define USE_STATIC_OPTIONS          (USB_DEVICE_OPT_FULLSPEED | USB_OPT_REG_ENABLED | USB_OPT_AUTO_PLL)
#define FIXED_CONTROL_ENDPOINT_SIZE 8
#define FIXED_NUM_CONFIGURATIONS    1

#define MAX_NUMBER_OF_KEYS 6

// General config
#define USB_DEVICE_VID 0x1209
#define USB_DEVICE_PID 0xF209
#define USB_DEVICE_PRODUCT L""
#define USB_DEVICE_MANUFACTURER L""
