name: "Build PCB gerbers"
on:
  push:
    paths:
      - "hardware-pcb/**"
      - ".github/workflows/build-hardware-pcb.yaml"

jobs:
  build-hardware-pcb:
    runs-on: ubuntu-latest
    steps:
      - name: "Get dependencies"
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          version: 1
          execute_install_scripts: true
          packages: kicad
      - name: "Checkout repo"
        uses: actions/checkout@v4
      - name: "Plot gerbers"
        run: kicad-cli pcb export gerbers hardware-pcb/JukeBox.kicad_pcb
    if: false # disable for now
  
  # TODO: use when kicad 7 is releases
  # https://docs.kicad.org/7.0/en/cli/cli.html
  # ALSO TODO: add kicad to dependencies cache