name: "Build firmware"
on:
  push:
    paths:
      - "firmware/**"
      - ".github/workflows/build-firmware.yaml"

jobs:
  build-firmware:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: "Update Rust"
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          target: thumbv6m-none-eabi
      - name: "Build Debug with Cargo"
        run: cd firmware/ && cargo build
      - name: "Build Release with Cargo"
        run: cd firmware/ && cargo build --release
      - name: "Upload Debug Artifact"
        uses: actions/upload-artifact@v4
        with:
          name: jb_firmware_debug
          path: firmware/target/thumbv6m-none-eabi/debug/jukebox_firmware
          retention-days: 90
      - name: "Upload Debug Artifact"
        uses: actions/upload-artifact@v4
        with:
          name: jb_firmware_release
          path: firmware/target/thumbv6m-none-eabi/release/jukebox_firmware
          retention-days: 90
