name: "Build JukeBox desktop app"
on:
  push:
    paths:
      - "software/**"

jobs:
  build-software:
    runs-on: ubuntu-latest
    steps:
      - name: "Get dependencies"
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          version: 1
          execute_install_scripts: true
          packages: libudev-dev cmake openscad gcc-mingw-w64 gcc-arm-none-eabi libnewlib-arm-none-eabi libstdc++-arm-none-eabi-newlib
      - name: "Rust setup"
        run: rustup target add x86_64-pc-windows-gnu && rustup update stable && rustup default stable && rustup toolchain list && rustup target list
      - name: "Checkout repo"
        uses: actions/checkout@v4
      - name: "Build software (Linux)"
        run: cd software/ && cargo build --release
      - name: "Upload artifact (Linux)"
        uses: actions/upload-artifact@v4
        with:
          name: jb-software-linux
          path: software/target/release/jukeboxcli
          retention-days: 90
      # TODO: fix windows builds
      # - name: "Build software (Windows)"
      #   run: cd software/ && cargo build --release --target x86_64-pc-windows-gnu && cd target/release/ && mv jukeboxcli jukeboxcli.exe
      # - name: "Upload artifact (Windows)"
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: jb-software-windows
      #     path: software/target/release/jukeboxcli.exe
      #     retention-days: 90
